services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard

  mongo:
    image: mongo
    restart: always
    env_file: ".env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT

  api-server:
    build:
      context: .
    depends_on:
      - mytb
      - mongo
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: $PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
      DB_DOMAIN: $DB_DOMAIN
      DB_NAME: $DB_NAME

    ports:
      - $PORT:$PORT
