name: api

on:
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
  push:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'

permissions:
  contents: read

concurrency:
  group: api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-api:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@eff65dc3f193f0a749872be82f74baa35be0797d # v1
        with:
          output: swagger-ui
          spec-file: api/open-api/swagger.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Audit dependencies
        working-directory: ./api
        run: npm audit --audit-level=high

      - name: Run unit tests
        working-directory: ./api
        run: npm test
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          DB_PREFIX: ${{ secrets.DB_PREFIX }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DOMAIN: ${{ secrets.DB_DOMAIN }}
          DB_NAME: ${{ secrets.DB_NAME }}
