name: Build project
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile proposal
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs/proposal
          root_file: proposal.tex

      - name: Compile final report
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs/final-report
          root_file: final-report.tex
  
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            docs/proposal/proposal.pdf
            docs/final-report/final-report.pdf
          overwrite: true
  build-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22] # Define a matrix of Node.js versions to test.There would be 3 jobs for 12.x, 14.x, 16.x

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.6
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          version: 3.1.0
          output: swagger-ui
          spec-file: api/open-api/swagger.yaml

      - name: Install dependencies
        working-directory: ./api 
        run: npm ci

      - name: Run unit tests 
        working-directory: ./api 
        run: npm test
        env:
          DB_CONNECTOR: ${{ secrets.DB_CONNECTOR }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

      - name: Run integration tests 
        working-directory: ./api 
        run: npm run test-int
        env:
          DB_CONNECTOR: ${{ secrets.DB_CONNECTOR }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
